# Generated by Django 3.0.7 on 2023-05-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_send_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send_mail',
        ),
    ]
