# Generated by Django 3.0.7 on 2023-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0009_listening_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='map',
            field=models.CharField(max_length=500),
        ),
    ]
