# Generated by Django 3.0.7 on 2023-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0010_auto_20230522_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='map',
            field=models.TextField(),
        ),
    ]
