# Generated by Django 3.0.7 on 2023-05-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0011_auto_20230522_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_message', models.TextField(max_length=200)),
            ],
        ),
    ]
