# Generated by Django 3.0.7 on 2023-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0014_auto_20230523_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedOtpMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_otp', models.CharField(max_length=4)),
            ],
        ),
    ]
