# Generated by Django 3.0.7 on 2023-05-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0015_receivedotpmail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivedOtpMail',
        ),
    ]
