# Generated by Django 3.0.7 on 2023-05-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0017_receivedmail_user_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceivedMail',
            new_name='CustomerMailRequest',
        ),
    ]
