# Generated by Django 3.0.7 on 2023-05-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0018_auto_20230526_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ('-created',), 'verbose_name': 'Listenings', 'verbose_name_plural': 'House Listings'},
        ),
    ]
